name: Update Stats

on:
  schedule:
    # Se lance toutes les 24h à minuit
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. Génère le Snake Game (Avec le TOKEN pour voir les contributions privées)
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Tot0le
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
        env:
          # On utilise ta nouvelle clé ici pour voir les commits privés
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}

      # 2. Génère les Habitudes (Avec le TOKEN pour scanner l'historique)
      - name: Generate Habits
        uses: lowlighter/metrics@latest
        with:
          filename: dist/stats.svg
          token: ${{ secrets.METRICS_TOKEN }} # Utilise ta clé ici aussi
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Europe/Paris

      # 3. Pousse le tout sur la branche "output"
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
