name: Update Stats

on:
  schedule:
    # Se lance toutes les 24h
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. Génère le Snake Game
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Tot0le
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 2. Génère les stats d'Habitudes (Matin/Soir) via Metrics
      # C'est LA référence pour remplacer WakaTime
      - name: Generate Habits
        uses: lowlighter/metrics@latest
        with:
          filename: dist/github-habits.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Europe/Paris

      # 3. Pousse tout ça dans la branche "output"
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
